import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AccessTokenContextProvider from './context/acess-token-context'
import Footer from './components/footer'
import ToasterContext from './context/toast-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotelify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>

      <body
        className={`${inter.className} h-full bg-gray-950 text-gray-50 flex flex-col items-center justify-center`}
      >
        <AccessTokenContextProvider>
          <ToasterContext />
          <main className="w-full h-full max-w-[800px] px-5">{children}</main>
        </AccessTokenContextProvider>
        <Footer />
      </body>
    </html>
  )
}
